export { default as SliderV1 } from "./SliderV1";
export { default as SliderV2 } from "./SliderV2";
export { default as SliderV3 } from "./SliderV3";
export { default as SliderV4 } from "./SliderV4";
export { default as CarouselSliderV1 } from "./CaroselSliderV1";
export { getSliderV1Code }     from "./SliderV1";
export { getSliderV2Code }     from "./SliderV2";
export { getSliderV3Code }     from "./SliderV3";
export { getSliderV4Code }     from "./SliderV4";
export { getCarouselSliderV1Code } from "./CaroselSliderV1";